import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  // English translations
  en: {
    translation: {
      firstName: "First Name",
      SearchInputRequired: "Search input is required",
      LocationInputRequired: "Location input is required",
      DateInputRequired: "Date input is required",
      NotFound: "Not Found",
      NotFoundDescription: "The page you are looking for does not exist.",
      Back: "Go back",
      About: "About",
      PricingHeading:
        "Explore Our Membership Options and Start Your Journey to Better Health",
      CompleteCode: "Complete the code",
      Doctors: "Doctors",
      Experts: "Introduce You to Our Experts",
      AskAQuestion: "Ask A Question",
      ExpertsDescription:
        "The list of certified doctors with years of professional experiences",
      Blog: "Blog",
      partner: "your Partner in Health and Wellness",
      FAQ: "Frequently Asked Questions",
      PrivacyPolicy: "Privacy Policy",
      TermsAndConditions: "Terms and Conditions",
      Services: "Services",
      lastName: "Last Name",
      email: "Email",
      Delma: "Delma",
      password: "Password",
      ProfileImage: "Profile Image",
      Home: "Home",
      ContactReason:
        "Kindly reach us to get the fastest response and treatment",
      Register: "Register",
      Appointments: "Appointments",
      DepartmentsHeading: "Get to Know Available Departments",
      DepartmentsDescription:
        "All medical departments at Dalma Healthcare Center are equipped with the latest technology and the best medical staff",
      FindDoctor: "Find Doctor",
      Offers: "Offers",
      FieldLength: "Each field must be 1 character",
      Contact: "Contact Us",
      Email: "Email",
      ContactUs: "Contact Us",
      Name: "Name",
      Subject: "Subject",
      Message: "Message",
      Departments: "Departments",
      Clinics: "Clinics",
      Hospitals: "Hospitals",
      Testimonials: "Testimonials",
      Hello: "Hello",
      DidNotReceiveEmail: "Did not receive email?",
      Resend: "Click here to resend",
      confirmPassword: "Confirm Password",
      WeAreHappy: "We are really happy to see you again!",
      phone: "Phone Number",
      gender: "Gender",
      Date: "Date",
      dateOfBirth: "Date of Birth",
      occupation: "Occupation",
      bloodType: "Blood Type",
      weight: "Weight (kg)",
      height: "Height (cm)",
      SendInstruction: "Send instructions",
      SentCode: "We sent a code to",
      city: "City",
      area: "Area",
      street: "Street",
      zipCode: "Zip Code",
      EmailRequired: "Email Required",
      FeaturedOffers: "Choose from top offers",
      ViewAllServices: "All Offers",
      SlotsLeft: "Left",
      All: "All",
      Cardiologist: "Cardiology",
      Neurologist: "Neurology",
      Audiologist: "Audiology",
      AllergyImmunologist: "Allergy & Immunology",
      Dermatologist: "Dermatology",
      Endocrinologist: "Endocrinology",
      Gastroenterologist: "Gastroenterology",
      Hematologist: "Hematology",
      AndrologistMaleInfertility: "Andrology & Male Infertility",
      Dentist: "Dentistry",
      DiabetesEndocrinologist: "Endocrinology & Diabetes",
      DietitianNutrition: "Nutrition & Dietetics",
      EarNoseAndThroat: "ENT (Ear, Nose & Throat)",
      GastroenterologistEndoscopy: "Gastroenterology & Endoscopy",
      GeneralSurgery: "General Surgery",
      Geriatrics: "Geriatrics",
      Gynecologist: "Gynecology",
      Hematologist: "Hematology",
      Nephrologist: "Nephrology",
      InternalMedicine: "Internal Medicine",
      GynecologistInfertility: "Gynecology & Female Infertility",
      Urologist: "Urology",
      Psychiatry: "Psychiatry",
      Phoniatrics: "Phoniatrics",
      PediatricsNewPorn: "Neonatology & Pediatrics",
      Rheumatologist: "Rheumatology",
      Physiotherapy: "Physiotherapy",
      Respiratorist: "Pulmonology",
      SpinalSurgery: "Spinal Surgery",
      PediatricsNewPorn: "Neonatology",
      Ophthalmologist: "Ophthalmology",
      Oncologist: "Oncology",
      ObsityLaparoscopic: "Obesity & Laparoscopic Surgery",
      Hepatologist: "Hepatology",
      personalInfo: "Personal Info",
      InvalidEmail: "Invalid email address",
      patientInfo: "Patient Info",
      addressInfo: "Address Info",
      registrationComplete: "Registration Complete!",
      ResetPassword: "Reset Your Password",
      GoToLogin: "Go to Login",
      Continue: "Continue",
      ResetPasswordMessage: "Your Password has been reset Successfully.",
      ConfirmPasswordRequired: "Confirm Password is required",
      LoginWithGoogle: "Login with Google",
      LoginWithFacebook: "Login with Facebook",
      BookAnAppointment: "Book an Appointment",
      thankYou:
        "Thank you for registering. You can now log in to your account.",
      goToLogin: "Go to Log In",
      back: "Back",
      SelectBloodType: "select blood type",
      next: "Next",
      completeRegistration: "Complete Registration",
      ForgotPassword: "Forgot Password?",
      SendMessage: "Send Message",
      Phone: "Phone",
      Location: "Location",
      CodeWarning: "Only 6 characters allowed",
      PasswordReset: "Password reset",
      pricing: "Pricing Plan",
      pricingDetails:
        "Explore Our Membership Options and Start Your Journey to Better Health",
      AboutUs: "About Us",
      Timetable: "Timetable",
      GetAdviceFromOurExperts:
        "To get the latest news about health from our experts",
      Subscription: "Be Our Subscribers",
      PasswordMinLength: "Password must be at least 8 characters long",
      PasswordRequired: "Password is required",
      Provide: "Provides Our",
      bestService: "Best Services",
      ExperiencedMedicalProfessionals: "Experienced Medical Professionals",
      ExperiencedMedicalProfessionalsContent:
        "Our team of doctors and healthcare professionals are highly experienced and qualified to provide you with the best care.",
      ComprehensiveServices: "Comprehensive Services approach",
      PatientCenteredApproach: "Patient-Centered Approach",
      PatientCenteredApproachContent:
        "We believe in treating each patient as an individual, and we take the time to understand your unique health needs and concerns.",
      ComprehensiveServicesContent:
        "We offer a wide range of healthcare services,from preventive care to specialized treatment for complex conditions.",
      StateOfTheArtFacilities: "State-of-the-Art Facilities",
      StateOfTheArtFacilitiesContent:
        "Our healthcare center is equipped with the latest technology and equipment to provide our patients with the most advanced care possible.",
      WhyChooseUs: "WHY CHOOSE US",
      DiagnosticTesting: "Diagnostic Testing",
      DiagnosticTestingCard:
        "Blood tests, imaging studies, and other tests to diagnose health conditions",
      RehabilitationServices: "Rehabilitation Services",
      RehabilitationServicesCard:
        "Physical therapy, occupational therapy, and other services to help patients recover from health conditions",
      MentalHealthServices: "Mental Health Services",
      HealthMonitoring: "Health Monitoring",
      PreventiveCare: "Preventive Care",
      PreventiveCareCard:
        "Annual checkups, immunizations, and health screenings",
      NoAccount: "Do not have an account ?",
      fullNameRequired: "full name is required",
      SubjectRequired: "Subject is required",
      MessageRequired: "Message is required",
      FirstNameRequired: "First name is required",
      newPasswordIsRequired: "New password is required",
      newPassword: "New password",
      OffersHeading: "Specialized Healthcare Packages Tailored for You",
      OffersDescription:
        "Take advantage of our specially designed medical packages that provide complete care pathways. Save on combined services while receiving coordinated treatment from our team of healthcare professionals.",
      CodeRequired: "Code Required",
      AllDone: "All Done",
      ChooseFromTopOffers: "Choose from top offers",
      Acupuncture: "Acupuncture",
      UpdatePassword: "Set Your New Password",
      HomeContent: "Your Health is Our Priority",
      HomeDescription:
        "We are committed to providing you with the best medical and healthcare services to help you live healthier and happier.",
      BookNow: "Book Now",
      searchway: "Search by doctor name or specialty",
      UpdatePasswordRequired:
        "Your New Password must be different from your old Password.",
      LastNameRequired: "Last name is required",
      PasswordsMustMatch: "Passwords must match",
      extraInfo:
        "You need to provide some extra info to complete your registration.",
      phoneNumberRequired: "Phone number is required",
      CopyRights: "Copyright © All rights reserved.",
      GenderRequired: "Gender is required",
      findUsHere: "find us here",
      "Already have an account": "Already have an account?",
      Submit: "Submit",
      WelcomeMessage: "Welcome to Delma ProHealth & HealthCare Center",
      EmailAlreadyExists: "Email already exists",
      HealthMonitoringCard:
        "Regular medical check-ups and ongoing monitoring of your health",
      MentalHealthServicesCard:
        "Counseling, therapy, and other services to help patients manage mental health conditions",
      FollowUs: "Follow Us",
      AdditionalServices: "Additional Services",
      Physiotherapy: "Physiotherapy",
      Orthodontics: "Orthodontics",
      DentalWhitening: "Dental Whitening",
      ViewAllOffers: "All Offers",
      NutritionalConsultation: "Nutritional Consultation",
      DoctorExpertise: "Choose Doctor Expertise",
      FeatureSectionHeading: "Providing the best medical services for you",
      FeatureSectionDescription:
        "World-class care for everyone. Our health System offers unmatched, expert health care",
      Login: "Login",
      language: "English (US)",
    },
  },
  ar: {
    translation: {
      WelcomeMessage: "مرحبا بكم في مركز دلما برو للصحة والرعاية الصحية",
      Services: "خدماتنا",
      firstName: "الاسم الأول",
      lastName: "الاسم الأخير",
      email: "البريد الإلكتروني",
      SearchInputRequired: "حقل البحث مطلوب",
      LocationInputRequired: "حقل الموقع مطلوب",
      DateInputRequired: "حقل التاريخ مطلوب",
      findUsHere: "تجدنا هنا",
      Doctors: "الدكاترة",
      FAQ: "أسئلة متكررة",
      ViewAllOffers: "كل العروض",
      Experts: "نقدم لكم خبرائنا",
      ExpertsDescription:
        "قائمة من الأطباء المعتمدين الذين يتمتعون بسنوات من الخبرة المهنية",
      partner: "شريكك في الصحة والعافية",
      FieldLength: "كل حقل يجب أن يحتوي علي عنصر واحد",
      OffersHeading: "خدمات الرعاية الصحية المصممة خصيصًا لك",
      OffersDescription:
        "استفد من باقاتنا الطبية المصممة خصيصًا التي توفر مسارات رعاية كاملة. احصل على خصومات عند دمج الخدمات مع تلقي العلاج المنسق من فريقنا من المتخصصين في الرعاية الصحية.",
      fullNameRequired: "الاسم كامل مطلوب",
      AdditionalServices: "الخدمات الاضافية",
      ChooseFromTopOffers: "اختار من عروضنا",
      Hospitals: "المستشفيات",
      Clinics: "العيادات",
      Physiotherapy: "العلاج الطبيعي",
      DentalWhitening: "تبيض أسنان",
      Orthodontics: "تقويم الأسنان",
      NutritionalConsultation: "استشارة تغذية",
      Acupuncture: "الوخز بالإبر",
      FeatureSectionHeading: "توفير أفضل الخدمات الطبية من أجلك",
      FeatureSectionDescription:
        "رعاية عالمية المستوى للجميع. يقدم نظامنا الصحي رعاية صحية متخصصة لا مثيل لها.",
      Continue: "متابعة",
      Blog: "المدونات",
      AboutUs: "معلومات عنا",
      newPassword: "كلمة المرور الجديدة",
      BookNow: "احجز الأن",
      AskAQuestion: "اسأل سؤال",
      Provide: "نقدم",
      bestService: "أفضل خدماتنا",
      DiagnosticTesting: "الاختبارات التشخيصية",
      DoctorExpertise: "اختار تخصص الدكتور",
      DiagnosticTestingCard:
        "اختبارات الدم ودراسات التصوير وغيرها من الاختبارات لتشخيص الحالات الصحية",
      RehabilitationServices: "خدمات إعادة التأهيل",
      RehabilitationServicesCard:
        "العلاج الطبيعي والعلاج المهني وخدمات أخرى لمساعدة المرضى على التعافي",
      MentalHealthServices: "خدمات الصحة العقلية",
      MentalHealthServicesCard:
        "الاستشارة والعلاج وغيرها من خدمات لمساعدة المرضى على إدارة حالات الصحة العقلية",
      HomeContent: "صحتك أولويتنا",
      HomeDescription:
        "نحن متلزمون بتزويدك بأفضل خدمات الرعاية الطبية و الصحية لمساعدتك علي العيش بصحة و سعادة أكبر",
      "Already have an account": "لديك حساب من قبل",
      HealthMonitoring: "المتابعة الصحية",
      HealthMonitoringCard: "الفحوصات الطبية المنتظمة وخدمات المراقبة المستمرة",
      PreventiveCare: "العناية الوقائية",
      PreventiveCareCard: "الفحوصات السنوية والتطعيمات والفحوصات الصحية",
      PricingHeading: "اختر خطة الأسعار المناسبة لك وابدأ رحلتك نحو صحة أفضل",
      confirmNewPassword: "تأكيد كلمة المرور الجديدة",
      SelectBloodType: "اختر فصيلة الدم",
      Departments: "الأقسام",
      Resend: "اضغط هنا لاعادة الارسال",
      SendInstruction: "ارسل التعليمات",
      DidNotReceiveEmail: "لم تستلم الكود ؟",
      ResetPassword: "استعادة كلمة المرور",
      SentCode: "تم ارسال الكود الي",
      ResetPasswordMessage: "تم تغير كلمة المرور بنجاح",
      UpdatePassword: "تغيير كلمة المرور",
      UpdatePasswordRequired:
        "يجب ان تكون كلمة المرور الجديدة مختلفة من كلمة المرور القديمة",
      ConfirmPasswordRequired: "تأكيد كلمة المرور مطلوب",
      pricing: "خطة الأسعار",
      pricingDetails: "استكشف خيارات عضويتنا وابدأ رحلتك نحو صحة أفضل",
      newPasswordIsRequired: "كلمة المرور الجديدة مطلوبة",
      CodeRequired: "الكود مطلوب",
      AllDone: "تمت بنجاح",
      GoToLogin: "العودة إلى تسجيل الدخول",
      extraInfo: "نحتاج إلى تقديم بعض المعلومات الإضافية لإكمال تسجيلك.",
      PrivacyPolicy: "سياسة الخصوصية",
      Testimonials: "الشهادات والتقييمات",
      ProfileImage: "الصورة الشخصية",
      Timetable: "الجداول",
      Offers: "العروض",
      TermsAndConditions: "الشروط والأحكام",
      password: "كلمة المرور",
      CopyRights: "جميع الحقوق محفوظة لسنة",
      confirmPassword: "تأكيد كلمة المرور",
      Contact: "تواصل معانا",
      ContactReason: "أحصل علي أسرع خدمة و علاج بأسرع طريقة ممكنة",
      Password: "كلمة المرور",
      ContactUs: "تواصل معانا من هنا",
      FollowUs: "تابعنا عبر منصات التواصل الإجتماعي",
      PasswordReset: "إعادة تعيين كلمة المرور",
      About: "حول",
      DepartmentsHeading: "تعرّف على الأقسام المتاحة",
      DepartmentsDescription:
        "جميع الأقسام الطبية المتوفرة في مركز دلما للرعاية الصحية، مجهزة بأحدث التقنيات وأفضل الكوادر الطبية",
      Name: "الإسم كاملا",
      Subject: "العنوان",
      SubjectRequired: "العنوان مطلوب",
      Message: "الرسالة",
      MessageRequired: "المحتوي مطلوب",
      Location: "الموقع",
      Date: "التاريخ",
      phone: "رقم الهاتف",
      Hello: "مرحبًا",
      gender: "الجنس",
      CompleteCode: "اكمل الكود",
      CodeWarning: "مسموح بـ ٦ أحرف فقط",
      dateOfBirth: "تاريخ الميلاد",
      female: "أنثي",
      Delma: "دلما",
      male: "ذكر",
      EmailRequired: "البريد الالكتروني مطلوب",
      InvalidEmail: "البريد الالكتروني غير صحيح",
      PasswordMinLength: "يجب أن تكون كلمة المرور على الأقل 8 حروف",
      FirstNameRequired: "الاسم الاول مطلوب",
      LastNameRequired: "الاسم الاخير مطلوب",
      PasswordRequired: "يجب ادخال كلمة المرور",
      Register: "حساب جديد",
      Email: "البريد الالكتروني",
      occupation: "المهنة",
      Subscription: "كن من مشتركينا",
      GetAdviceFromOurExperts: "للحصول علي أجدد الأخبار عن الصحة من خبرائنا",
      Submit: "ارسل",
      bloodType: "فصيلة الدم",
      weight: "الوزن (كجم)",
      height: "الطول (سم)",
      city: "المدينة",
      area: "المنطقة",
      Phone: "رقم التواصل",
      PasswordsMustMatch: "يجب ان تكون كلمتي المرور متطابقتين ",
      Login: "تسجيل الدخول",
      LoginWithGoogle: "تسجيل الدخول باستخدام جوجل",
      LoginWithFacebook: "تسجيل الدخول باستخدام فيسبوك",
      street: "الشارع",
      zipCode: "الرمز البريدي",
      personalInfo: "المعلومات الشخصية",
      Appointments: "المواعيد",
      patientInfo: "معلومات المريض",
      addressInfo: "معلومات العنوان",
      GenderRequired: "الجنس مطلوب",
      SendMessage: "إرسال الرسالة",
      registrationComplete: "تم التسجيل بنجاح!",
      thankYou: "شكرًا لتسجيلك. يمكنك الآن تسجيل الدخول إلى حسابك.",
      phoneNumberRequired: "الرقم الموبايل مطلوب",
      WeAreHappy: "نحن سعداء جدا لرؤيتك مرة اخرى!",
      Home: "الصفحة الرئيسية",
      FindDoctor: "ابحث عن طبيب",
      searchway: "ابحث عن طبيبك عن طريق التخصص أو الاسم",
      NotFound: "الصفحة غير موجودة",
      NotFoundDescription: "الصفحة التي تبحث عنها غير موجودة.",
      Back: "العودة إلى الصفحة السابقة",
      goToLogin: "انتقل إلى تسجيل الدخول",
      back: "رجوع",
      ForgotPassword: "نسيت كلمة المرور؟",
      next: "التالي",
      completeRegistration: "إكمال التسجيل",
      Signup: "تسجيل حساب جديد",
      NoAccount: "ليس لديك حساب؟",
      language: "العربية",
      ExperiencedMedicalProfessionals: "متخصصون طبيون ذوو خبرة",
      ExperiencedMedicalProfessionalsContent:
        "فريقنا من الأطباء والمتخصصين في الرعاية الصحية يتمتعون بخبرة عالية ومؤهلات ممتازة لتقديم أفضل رعاية لكم.",
      ComprehensiveServices: "نهج الخدمات الشاملة",
      PatientCenteredApproach: "نهج يركز على المريض",
      PatientCenteredApproachContent:
        "نؤمن بمعالجة كل مريض كفرد، ونأخذ الوقت الكافي لفهم احتياجاتك الصحية الفريدة ومخاوفك.",
      ComprehensiveServicesContent:
        "نقدم مجموعة واسعة من الخدمات الصحية، من الرعاية الوقائية إلى العلاج المتخصص للحالات المعقدة.",
      StateOfTheArtFacilities_ar: "مرافق حديثة",
      StateOfTheArtFacilitiesContent_ar:
        "مركزنا الصحي مجهز بأحدث التقنيات والمعدات لتقديم أفضل رعاية متقدمة لمرضانا",
      WhyChooseUs: "لماذا نحن",
      BookAnAppointment: "احجز موعد",
    },
  },
};

// Get saved language from localStorage or default to English
const savedLanguage = localStorage.getItem("defaultLanguage") || "en";

i18n.use(initReactI18next).init({
  resources,
  lng: savedLanguage,
  fallbackLng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
