import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  // English translations
  en: {
    translation: {
      firstName: "First Name",
      NotFound: "Not Found",
      NotFoundDescription: "The page you are looking for does not exist.",
      Back: "Go back",
      About: "About",
      PricingHeading: "Explore Our Membership Options and Start Your Journey to Better Health",
      CompleteCode: "Complete the code",
      Doctors: "Doctors",
      Experts: "Introduce You to Our Experts",
      ExpertsDescription: 'The list of certified doctors with years of professional experiences',
      Blog: "Blog",
      partner: "your Partner in Health and Wellness",
      FAQ: "Frequently Asked Questions",
      PrivacyPolicy: "Privacy Policy",
      TermsAndConditions: "Terms and Conditions",
      Services: "Services",
      lastName: "Last Name",
      email: "Email",
      Delma: "Delma",
      password: "Password",
      Home: "Home",
      ContactReason: "Kindly reach us to get the fastest response and treatment",
      Register: "Register",
      Appointments: "Appointments",
      FindDoctor: 'Find Doctor',
      FieldLength: "Each field must be 1 character",
      Contact: 'Contact Us',
      Email:"Email",
      ContactUs: "Contact Us",
      Name: 'Name',
      Subject:"Subject",
      Message: "Message",
      Departments: "Departments",
      Testimonials: "Testimonials",
      Hello: "Hello",
      DidNotReceiveEmail: 'Did not receive email?',
      Resend: 'Click here to resend',
      confirmPassword: "Confirm Password",
      WeAreHappy: "We are really happy to see you again!",
      phone: "Phone Number",
      gender: "Gender",
      dateOfBirth: "Date of Birth",
      occupation: "Occupation",
      bloodType: "Blood Type",
      weight: "Weight (kg)",
      height: "Height (cm)",
      SendInstruction: "Send instructions",
      SentCode: "We sent a code to",
      city: "City",
      area: "Area",
      street: "Street",
      zipCode: "Zip Code",
      EmailRequired: "Email Required",
      personalInfo: "Personal Info",
      InvalidEmail: "Invalid email address",
      patientInfo: "Patient Info",
      addressInfo: "Address Info",
      registrationComplete: "Registration Complete!",
      ResetPassword :'Reset Your Password',
      GoToLogin: "Go to Login",
      Continue: "Continue",
      ResetPasswordMessage: "Your Password has been reset Successfully.",
      ConfirmPasswordRequired: "Confirm Password is required",
      LoginWithGoogle: "Login with Google",
      LoginWithFacebook: "Login with Facebook",
      thankYou:"Thank you for registering. You can now log in to your account.",
      goToLogin: "Go to Log In",
      back: "Back",
      SelectBloodType:"select blood type",
      next: "Next",
      completeRegistration: "Complete Registration",
      ForgotPassword: "Forgot Password?",
      SendMessage: 'Send Message',
      Phone: "Phone",
      Location: "Location",
      CodeWarning: 'Only 6 characters allowed',
      PasswordReset: "Password reset",
      pricing: "Pricing Plan",
      pricingDetails: 'Explore Our Membership Options and Start Your Journey to Better Health',
      AboutUs: 'About Us',
      Timetable: "Timetable",
      GetAdviceFromOurExperts: 'To get the latest news about health from our experts',
      Subscription: "Be Our Subscribers",
      PasswordMinLength: 'Password must be at least 8 characters long',
      PasswordRequired: 'Password is required',
      Provide: "Provides Our",
      bestService: 'Best Services',
      DiagnosticTesting: 'Diagnostic Testing',
      DiagnosticTestingCard: 'Blood tests, imaging studies, and other tests to diagnose health conditions',
      RehabilitationServices: 'Rehabilitation Services',
      RehabilitationServicesCard: 'Physical therapy, occupational therapy, and other services to help patients recover from health conditions',
      MentalHealthServices: 'Mental Health Services',
      HealthMonitoring: 'Health Monitoring',
      PreventiveCare: 'Preventive Care',
      PreventiveCareCard: 'Annual checkups, immunizations, and health screenings',
      NoAccount: "Do not have an account ?", 
      FirstNameRequired: "First name is required",
      newPasswordIsRequired: "New password is required",
      newPassword: "New password",
      CodeRequired: "Code Required",
      AllDone: "All Done",
      UpdatePassword: "Set Your New Password",
      UpdatePasswordRequired: "Your New Password must be different from your old Password.",
      LastNameRequired: "Last name is required",
      PasswordsMustMatch: "Passwords must match",
      extraInfo: "You need to provide some extra info to complete your registration.",
      phoneNumberRequired: "Phone number is required",
      CopyRights: "Copyright © 2024 All rights reserved.",
      GenderRequired: "Gender is required",
      findUsHere: "find us here",
      Submit: "Submit",
      WelcomeMessage: "Welcome to Delma ProHealth & HealthCare Center",
      EmailAlreadyExists: "Email already exists",
      FollowUs: "Follow Us",
      Login: "Login",
      language: "English (US)",
    },
},
  ar: {
    translation: {
      WelcomeMessage: "مرحبا بكم في مركز دلما برو للصحة والرعاية الصحية",
      Services: "خدماتنا",
      firstName: 'الاسم الأول',
      lastName: 'الاسم الأخير',
      email: 'البريد الإلكتروني',
      findUsHere: 'تجدنا هنا',
      Doctors: 'الدكاترة',
      FAQ: 'أسئلة متكررة',
      Experts: 'نقدم لكم خبرائنا',
      ExpertsDescription: 'قائمة من الأطباء المعتمدين الذين يتمتعون بسنوات من الخبرة المهنية',
      partner: 'شريكك في الصحة والعافية',
      FieldLength: 'كل حقل يجب أن يحتوي علي عنصر واحد',
      Continue: 'متابعة',
      Blog: 'المدونات',
      AboutUs: 'معلومات عنا',
      newPassword: 'كلمة المرور الجديدة',
      Provide: 'نقدم',
      bestService: 'أفضل خدماتنا',
      DiagnosticTesting: 'الاختبارات التشخيصية',
      DiagnosticTestingCard:'اختبارات الدم ودراسات التصوير وغيرها من الاختبارات لتشخيص الحالات الصحية',
      RehabilitationServices:'خدمات إعادة التأهيل',
      RehabilitationServicesCard: 'العلاج الطبيعي والعلاج المهني وخدمات أخرى لمساعدة المرضى على التعافي',
      MentalHealthServices: 'خدمات الصحة العقلية',
      HealthMonitoring: 'المتابعة الصحية',
      HealthMonitoringCard: 'الفحوصات الطبية المنتظمة وخدمات المراقبة المستمرة',
      PreventiveCare: 'العناية الوقائية',
      PreventiveCareCard: 'الفحوصات السنوية والتطعيمات والفحوصات الصحية',
      PricingHeading: 'اختر خطة الأسعار المناسبة لك وابدأ رحلتك نحو صحة أفضل',
      confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
      SelectBloodType: 'اختر فصيلة الدم',
      Departments: 'الأقسام',
      Resend: "اضغط هنا لاعادة الارسال",
      SendInstruction: 'ارسل التعليمات',
      DidNotReceiveEmail:'لم تستلم الكود ؟',
      ResetPassword: 'استعادة كلمة المرور',
      SentCode: 'تم ارسال الكود الي',
      ResetPasswordMessage: 'تم تغير كلمة المرور بنجاح',
      UpdatePassword: 'تغيير كلمة المرور',
      UpdatePasswordRequired: 'يجب ان تكون كلمة المرور الجديدة مختلفة من كلمة المرور القديمة',
      ConfirmPasswordRequired: 'تأكيد كلمة المرور مطلوب',
      pricing: "خطة الأسعار",
      pricingDetails: 'استكشف خيارات عضويتنا وابدأ رحلتك نحو صحة أفضل',
      newPasswordIsRequired: 'كلمة المرور الجديدة مطلوبة',
      CodeRequired: 'الكود مطلوب',
      AllDone: 'تمت بنجاح',
      GoToLogin: 'العودة إلى تسجيل الدخول',
      extraInfo: 'نحتاج إلى تقديم بعض المعلومات الإضافية لإكمال تسجيلك.',
      PrivacyPolicy: 'سياسة الخصوصية',
      Testimonials: 'الشهادات والتقييمات',
      Timetable: 'الجداول',
      TermsAndConditions: 'الشروط والأحكام',
      password: 'كلمة المرور',
      CopyRights: 'جميع الحقوق محفوظة لسنة ٢٠٢٤',
      confirmPassword: 'تأكيد كلمة المرور',
      Contact: "تواصل معانا",
      ContactReason: 'أحصل علي أسرع خدمة و علاج بأسرع طريقة ممكنة',
      Password: 'كلمة المرور',
      ContactUs: 'تواصل معانا من هنا',
      FollowUs: 'تابعنا عبر منصات التواصل الإجتماعي',
      PasswordReset: 'إعادة تعيين كلمة المرور',
      About: "حول",
      Name: 'الإسم كاملا',
      Subject: 'العنوان',
      Message: 'الرسالة',
      Location: 'الموقع',
      phone: 'رقم الهاتف',
      Hello: 'مرحبًا',
      gender: 'الجنس',
      CompleteCode: 'اكمل الكود',
      CodeWarning: 'مسموح بـ ٦ أحرف فقط',
      dateOfBirth: 'تاريخ الميلاد',
      female: 'أنثي',
      Delma: 'دلما',
      male:'ذكر',
      EmailRequired: 'البريد الالكتروني مطلوب',
      InvalidEmail: 'البريد الالكتروني غير صحيح',
      PasswordMinLength: 'يجب أن تكون كلمة المرور على الأقل 8 حروف',
      FirstNameRequired: 'الاسم الاول مطلوب',
      LastNameRequired: 'الاسم الاخير مطلوب',
      PasswordRequired: 'يجب ادخال كلمة المرور',
      Register: 'حساب جديد',
      Email: "البريد الالكتروني",
      occupation: 'المهنة',
      Subscription: 'كن من مشتركينا',
      GetAdviceFromOurExperts: 'للحصول علي أجدد الأخبار عن الصحة من خبرائنا',
      Submit: 'ارسل',
      bloodType: 'فصيلة الدم',
      weight: 'الوزن (كجم)',
      height: 'الطول (سم)',
      city: 'المدينة',
      area: 'المنطقة',
      Phone: "رقم التواصل",
      PasswordsMustMatch: 'يجب ان تكون كلمتي المرور متطابقتين ',
      Login: 'تسجيل الدخول',
      LoginWithGoogle: "تسجيل الدخول باستخدام جوجل",
      LoginWithFacebook: "تسجيل الدخول باستخدام فيسبوك",
      street: 'الشارع',
      zipCode: 'الرمز البريدي',
      personalInfo: 'المعلومات الشخصية',
      Appointments: 'المواعيد',
      patientInfo: 'معلومات المريض',
      addressInfo: 'معلومات العنوان',
      GenderRequired: 'الجنس مطلوب',
      SendMessage: 'إرسال الرسالة',
      registrationComplete: 'تم التسجيل بنجاح!',
      thankYou: 'شكرًا لتسجيلك. يمكنك الآن تسجيل الدخول إلى حسابك.',
      phoneNumberRequired: 'الرقم الموبايل مطلوب',
      WeAreHappy: 'نحن سعداء جدا لرؤيتك مرة اخرى!',
      Home: 'الصفحة الرئيسية',
      FindDoctor: 'ابحث عن طبيب',
      NotFound: 'الصفحة غير موجودة',
      NotFoundDescription: 'الصفحة التي تبحث عنها غير موجودة.',
      Back: 'العودة إلى الصفحة السابقة',
      goToLogin: 'انتقل إلى تسجيل الدخول',
      back: 'رجوع',
      ForgotPassword: 'نسيت كلمة المرور؟',
      next: 'التالي',
      completeRegistration: 'إكمال التسجيل',
      Signup: "تسجيل حساب جديد",
      NoAccount: "ليس لديك حساب؟",
      language: "العربية",
    },
  },
};

// Get saved language from localStorage or default to English
const savedLanguage = localStorage.getItem("defaultLanguage") || "en";

i18n.use(initReactI18next).init({
  resources,
  lng: savedLanguage,
  fallbackLng: "en", 
  interpolation: {
    escapeValue: false,
  },
});


export default i18n;